### ISSUE TITLE
[bug] Custom Torch does not render.

### ISSUE THREAD

**Issue by ItsDrCat** [MADLAD3718/Offhand-Torches-RTX#1]
![Minecraft 11_6_2023 5_26_58 PM](https://github.com/MADLAD3718/Offhand-Torches-RTX/assets/114036615/4480aedd-46d9-4708-a776-6dc1a8ff4652)
I've had this problem before and it's typically when you go over 50% transparent.

**Comment by MADLAD3718** [comment]
This should already be resolved with a change to the texure I made a while ago. The current release file presumably didn't include this fix, but the next one definitely will.
